; =========================
; 规则集定义
; =========================


; ===== 私人定制 =====
ruleset=🎯 全球直连,https://raw.githubusercontent.com/Gufiye/Rule/refs/heads/main/Direct.list
ruleset=🚀 全球代理,https://raw.githubusercontent.com/Gufiye/Rule/refs/heads/main/Global.list


; ===== 本地 / 国内直连优先 =====
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list


; ===== 金融 / 系统级=====
ruleset=🎯 Futunn,https://raw.githubusercontent.com/Gufiye/Rule/refs/heads/main/Futu.list
ruleset=👛 Paypal,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/PayPal/PayPal.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=⭐ SAMSUNG,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Samsung/Samsung.list


; ===== AI 服务 =====
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini.list
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Copilot/Copilot.list
ruleset=🤖 AI,https://raw.githubusercontent.com/Gufiye/Rule/refs/heads/main/Grok.list


; ===== 流媒体 =====
ruleset=🎥 Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎵 Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Spotify/Spotify.list
ruleset=🎵 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=📘 Meta,https://raw.githubusercontent.com/Gufiye/Rule/refs/heads/main/Meta.list

; ===== 通讯 / 社交 =====
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=📢 FCM,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=🐦 X,https://raw.githubusercontent.com/Gufiye/Rule/refs/heads/main/X.list
ruleset=🧨 TruthSocial,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TruthSocial/TruthSocial.list

; ===== 云服务 / 开发 =====
ruleset=👨🏿‍💻 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=🐬 OneDrive,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
ruleset=🪟 Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍀 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=♻️ Speedtest,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list


; ===== 游戏平台 =====
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list


; ===== 媒体 =====
ruleset=🎞️ 国内媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list


; ===== GFW / 大范围代理 =====
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list


; ===== GEO 规则（兜底逻辑）=====
ruleset=🎯 全球直连,[]GEOSITE,CN
ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve


; ===== 最终兜底 =====
ruleset=🐟 漏网之鱼,[]FINAL















# =========================
# 核心入口
# =========================
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动测速`[]🇹🇼 台湾节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇪🇺 欧盟节点`[]🍃 香港自动`[]🍃 日本自动`[]🍃 台湾自动`[]🍃 加坡自动`[]🍃 美国自动`[]🔯 香港故转`[]🔯 日本故转`[]🔯 台湾故转`[]🔯 加坡故转`[]🔯 美国故转`[]⚖️ 香港均衡`[]⚖️ 台湾均衡`[]⚖️ 美国均衡`[]🌐 其他地区`[]🐸 手动切换`[]DIRECT
custom_proxy_group=♻️ 自动测速`url-test`(?=.*(香港|HK|Hong Kong|🇭🇰|日本|JP|Japan|新加坡|SG|Singapore|台湾|TW|Taiwan))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🐸 手动切换`select`.*

# =========================
# 流媒体 / AI / 常用服务
# =========================
custom_proxy_group=📹 YouTube`select`[]🚀 节点选择`[]🍃 香港自动`[]🍃 日本自动`[]🍃 台湾自动`[]🍃 加坡自动`[]🍃 美国自动`[]⚖️ 香港均衡`[]⚖️ 台湾均衡`[]⚖️ 美国均衡`[]🐸 手动切换`[]♻️ 自动测速
custom_proxy_group=🎥 Netflix`select`[]🎬 Netflix`[]🎬 Netflix自动`[]🎬 Netflix故转`
custom_proxy_group=🎵 Spotify`select`[]DIRECT`[]🇹🇼 台湾节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇺🇸 美国节点`[]⚖️ 香港均衡`[]⚖️ 台湾均衡`[]⚖️ 美国均衡`[]🐸 手动切换`[]🚀 节点选择
custom_proxy_group=🎵 TikTok`select`[]🚀 节点选择`[]🍃 日本自动`[]🍃 台湾自动`[]🍃 加坡自动`[]🍃 美国自动`[]⚖️ 台湾均衡`[]⚖️ 美国均衡`[]🐸 手动切换`[]♻️ 自动测速
custom_proxy_group=🤖 AI`select`[]🚀 节点选择`[]🔯 日本故转`[]🔯 加坡故转`[]🔯 台湾故转`[]🔯 美国故转`[]🍃 台湾自动`[]🍃 美国自动`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇹🇼 台湾节点`[]🇺🇸 美国节点`[]🐸 手动切换
custom_proxy_group=📘 Meta`select`[]🚀 节点选择`[]🍃 香港自动`[]🍃 日本自动`[]🍃 台湾自动`[]🍃 加坡自动`[]🍃 美国自动`[]🐸 手动切换`[]♻️ 自动测速
custom_proxy_group=🎯 Futunn`select`[]DIRECT`[]🚀 节点选择`[]🍃 香港自动`[]🔯 香港故转`[]🇭🇰 香港节点`[]⚖️ 香港均衡`[]🐸 手动切换
custom_proxy_group=🧨 TruthSocial`select`[]🚀 节点选择`[]🍃 美国自动`[]🔯 美国故转`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]⚖️ 美国均衡`[]🐸 手动切换



# =========================
# 云服务 / 大厂/ 设备 / 系统 / 工具
# =========================
custom_proxy_group=🐬 OneDrive`select`[]🚀 节点选择`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 美国故转`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]⚖️ 香港均衡`[]⚖️ 台湾均衡`[]⚖️ 美国均衡`[]🛩️ 高速节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🪟 Microsoft`select`[]🚀 节点选择`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 美国故转`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]⚖️ 香港均衡`[]⚖️ 台湾均衡`[]⚖️ 美国均衡`[]🛩️ 高速节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🍀 Google`select`[]🚀 节点选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🔯 台湾故转`[]🔯 美国故转`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇹🇼 台湾节点`[]🇺🇸 美国节点`[]⚖️ 香港均衡`[]⚖️ 台湾均衡`[]⚖️ 美国均衡`[]🛩️ 高速节点`[]🐸 手动切换
custom_proxy_group=👨🏿‍💻 GitHub`select`[]🚀 节点选择`[]🔯 香港故转`[]🔯 台湾故转`[]🔯 美国故转`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]⚖️ 香港均衡`[]⚖️ 台湾均衡`[]⚖️ 美国均衡`[]🛩️ 高速节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=📲 Telegram`select`[]🚀 节点选择`[]🍃 香港自动`[]🍃 日本自动`[]🍃 台湾自动`[]🍃 加坡自动`[]🍃 美国自动`[]⚖️ 香港均衡`[]⚖️ 台湾均衡`[]⚖️ 美国均衡`[]🐸 手动切换`[]♻️ 自动测速
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🐸 手动切换`[]🚀 节点选择
custom_proxy_group=⭐ SAMSUNG`select`[]DIRECT`[]🐸 手动切换`[]🚀 节点选择
custom_proxy_group=♻️ Speedtest`select`[]DIRECT`[]🇹🇼 台湾节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇺🇸 美国节点`[]🐸 手动切换`[]🚀 节点选择
custom_proxy_group=👛 Paypal`select`[]DIRECT`[]🇹🇼 台湾节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇺🇸 美国节点`[]🐸 手动切换`[]🚀 节点选择
custom_proxy_group=🐦 X`select`[]🚀 节点选择`[]🍃 香港自动`[]🍃 日本自动`[]🍃 台湾自动`[]🍃 加坡自动`[]🍃 美国自动`[]🐸 手动切换`[]♻️ 自动测速

# =========================
#  游戏 / 杂项
# =========================
custom_proxy_group=📢 FCM`select`[]DIRECT`[]🐸 手动切换
custom_proxy_group=🎮 游戏平台`select`[]🚀 节点选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🔯 台湾故转`[]🔯 美国故转`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇹🇼 台湾节点`[]🇺🇸 美国节点`[]🛩️ 高速节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🎞️ 国内媒体`select`[]DIRECT`[]🚀 节点选择`[]🐸 手动切换
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]🐸 手动切换
custom_proxy_group=🚀 全球代理`select`[]🚀 节点选择`[]🔯 香港故转`[]🔯 日本故转`[]🔯 加坡故转`[]🔯 台湾故转`[]🔯 美国故转`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`[]🇹🇼 台湾节点`[]🇺🇸 美国节点`[]🛩️ 高速节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🐸 手动切换`[]DIRECT


# =========================
# 节点分类
# =========================
custom_proxy_group=🏡 家宽节点`select`(家宽|家庭)
custom_proxy_group=🛩️ 高速节点`select`(香港|HK|日本|JP|台湾|TW|韩国|越南|马来西亚|泰国)

custom_proxy_group=🇭🇰 香港节点`select`(?=.*(香港|HK|Hong Kong|🇭🇰)).*
custom_proxy_group=🇹🇼 台湾节点`select`(?=.*(台湾|台灣|TW|Taiwan|🇹🇼))(?!.*🇭🇰).*
custom_proxy_group=🇯🇵 日本节点`select`(?=.*(日本|东京|大阪|JP|Japan|🇯🇵))(?!.*🇭🇰).*
custom_proxy_group=🇸🇬 加坡节点`select`(?=.*(新加坡|坡|狮城|SG|Singapore|🇸🇬))(?!.*🇭🇰).*
custom_proxy_group=🇺🇸 美国节点`select`^(?=.*(美国|US|United States|🇺🇸))(?!.*🇭🇰).*
custom_proxy_group=🇬🇧 英国节点`select`(?=.*(英国|UK|United Kingdom|GB|🇬🇧)).*
custom_proxy_group=🇪🇺 欧盟节点`select`(?=.*(法国|西班牙|德国|荷兰|瑞典|土耳其|意大利)).*
custom_proxy_group=🌐 其他地区`select`(^(?!.*(香港|HK|Hong Kong|🇭🇰|日本|JP|Japan|台湾|台灣|TW|Taiwan|🇹🇼|新加坡|坡|狮城|SG|Singapore|美国|US|United States|英国|UK|United Kingdom|GB|法国|西班牙|德国|荷兰|瑞典|土耳其|意大利)).*)
custom_proxy_group=🎬 Netflix`select`(?=.*(Netflix|NF|奈飞)).*


# =========================
# 自动测速（url-test)
# =========================
custom_proxy_group=🍃 香港自动`url-test`(?=.*(香港|HK|Hong Kong|🇭🇰))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🍃 台湾自动`url-test`(?=.*(台湾|台灣|TW|Taiwan|🇹🇼))(?!.*🇭🇰)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🍃 日本自动`url-test`(?=.*(日本|JP|Japan))(?!.*🇭🇰)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🍃 加坡自动`url-test`(?=.*(新加坡|坡|狮城|SG|Singapore))(?!.*🇭🇰)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🍃 美国自动`url-test`(?=.*(美国|US|United States|🇺🇸))(?!.*🇭🇰)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🎬 Netflix自动`url-test`(?=.*(Netflix|NF|奈飞))`http://www.gstatic.com/generate_204`300,,50


# =========================
# 故障转移（Fallback）
# =========================
custom_proxy_group=🔯 香港故转`fallback`(?=.*(香港|HK|Hong Kong|🇭🇰))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 日本故转`fallback`(?=.*(日本|JP|Japan))(?!.*🇭🇰)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 台湾故转`fallback`(?=.*(台湾|台灣|TW|Taiwan|🇹🇼))(?!.*🇭🇰)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 加坡故转`fallback`(?=.*(新加坡|坡|狮城|SG|Singapore))(?!.*🇭🇰)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 美国故转`fallback`(?=.*(美国|US|United States|🇺🇸))(?!.*🇭🇰)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🎬 Netflix故转`fallback`(?=.*(Netflix|NF|奈飞))`http://www.gstatic.com/generate_204`300,,50

# =========================
# 负载均衡（三地区）
# =========================

custom_proxy_group=⚖️ 香港均衡`load-balance`(?=.*(香港|HK|Hong Kong|🇭🇰))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=⚖️ 台湾均衡`load-balance`(?=.*(台湾|台灣|TW|Taiwan|🇹🇼))(?!.*🇭🇰)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=⚖️ 美国均衡`load-balance`(?=.*(美国|US|United States|🇺🇸))(?!.*🇭🇰)`http://www.gstatic.com/generate_204`300,,50
;启用自定义规则集

enable_rule_generator=true
overwrite_original_rules=true

